### ISSUE TITLE
ThemeBuilder swatch does not contain all default Kendo Theme styles

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#103]
**Describe the bug**

When changing the color swatch to A11y (of the Default theme, but reproducible with other themes), not all related code changes are propagated in ThemeBuilder. As a result, not all specific A11y styles are available in a ThemeBuilder project that uses A11y swatch.

**To Reproduce**
1. Create a Kendo **Default** project.
2. Change the color swatch to **Default Ocean Blue A11y**
3. Export the theme and observe the differences in the TB-generated CS compared to the original CSS for **Default Ocean Blue A11y**

For example, observe the generated code for `.k-button-solid-base.k-focus`
```CSS
.k-button-solid-base:focus,
.k-button-solid-base.k-focus {
    box-shadow: 0 0 0 2px color-mix(in srgb, var(--kendo-color-on-app-surface, #424242) 8%, transparent)
}
```

**Expected**

TO generate the CSS as per the Kendo Default swatch

```CSS
.k-button-solid-base:focus,
.k-button-solid-base.k-focus {
    box-shadow: inset 0 0 0 2px currentColor;
}
```

**Screenshots**

**Components technology and version**
TB Q2 2024, TB Q3 2024 with Kendo Default 8.x.x

**Additional context**
Reported through t. 1660336
