### ISSUE TITLE
Simplify templates for ButtonGroup

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#107]
**Describe the bug**
Currently, the ButtonGroup has templates for **Solid**, **Flat**, and **Outline** buttons.
However, some changes are applied to all configurations, regardless of the button fill mode or theme color.

For example, this is the CSS generated when setting a border-radius for the **Flat** normal button

```CSS
.k-button-group .k-button:not(:first-child):not(:last-child) {
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
    border-top-left-radius: 20px;
    border-top-right-radius: 20px;
}
```

As a result, all other buttons (other than the first and last) will have the same styles (even if they are not flat).

The above means that we should probably remove the fill mode templates and leave only templates for the **first**, **last**, and **middle** buttons in the context of the ButtonGroup component. Then, the styling for the buttons will always come from the Button configurations.

**To Reproduce**
1. Go to 'ButtonGroup'
2. Set border-radius for the **Flat/Text** > **Button** template
3. The border-radius is also applied for the **Solid/Text > Button** template

**Expected behavior**

To create styles for first, last, and middle buttons and not to be able to set styles for specific fill modes and theme colors as these are configured explicitly by the user during the creation of the ButtonGroup component and should be styled from within the Button configurations.

**Screenshots**
![image](https://github.com/user-attachments/assets/1d1a06aa-2828-46f5-afa6-18f2002fbbec)

**Components technology and version**
TB Q2 2024

**Additional context**
Reported through t.1661317 and internal MS Teams communication
