### ISSUE TITLE
Enable support for URL in external CSS

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#112]
**Description**
Currently, you can import external CSS that contains URL
![image](https://github.com/user-attachments/assets/b7a63244-1256-4b8a-a68a-2d7ea31331eb)

Example CSS
![image](https://github.com/user-attachments/assets/fff02e0d-a0dd-4f92-9f28-9fc8595bd50b)

However, ThemeBuilder already supports URLs for background images in HTML, so we should also enable the support in external CSS files.

**Scenarios to Cover**
- [x] Supporting URLs in external CSS will allow the import of CSS files that contain SVG images

**Additional context**
Reproducible in TB Q3 2024

- [ ] ~Issue 1- The uses cases form the comment are still reproducible~

**Comment by petar-i-todorov** [comment]
+1 from t.1666246.

Allow using the url functions inside `@font-face` and `@import` at-rules:
```css
@font-face {
    font-family: 'Roboto';
    src: url('https://cdn.jsdelivr.net/npm/@fontsource/roboto/files/roboto-latin-400-normal.woff2') format('woff2'),
        url('https://cdn.jsdelivr.net/npm/@fontsource/roboto/files/roboto-latin-400-normal.woff') format('woff');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}
```

```css
@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap");
```

Use case - this would enable users to use fonts in ThemeBuilder, even if their (font) licenses prohibit direct file uploads.
