### ISSUE TITLE
Generated styles for TileLayout > Tile Layout Item (div) have an additional .k-cursor-grab selector

### ISSUE THREAD

**Issue by petar-i-todorov** [telerik/themebuilder#123]
**Describe the bug**
Generated styles for the cards of the TileLayout have an additional .k-cursor-grab selector. However, this class is [specific to KendoReact](https://github.com/search?q=repo%3Atelerik%2Fkendo-react-private%20k-cursor-grab&type=code) and is not part of the component based on the [rendering truth](https://github.com/telerik/kendo-themes/blob/develop/tests/tilelayout/tilelayout.html#L27). This leads to styles generated from ThemeBuilder for that component part not being applied in other technologies.

**To Reproduce**
1. Create a new project.
2. Apply styles to TileLayout > Tile Layout Item (div).
3. Export the package.
4. Check the styles from the package and the [rendering truth](https://github.com/telerik/kendo-themes/blob/develop/tests/tilelayout/tilelayout.html#L27).

**Actual Results**
Generated styles include the .k-cursor-grab selector, but the rendering truth does not have this class.

```css
.k-tilelayout .k-tilelayout-item.k-card.k-cursor-grab {
    box-shadow: 0px 8px 10px 0 rgba(0, 0, 0, .12), 0px 4px 16px 0 rgba(0, 0, 0, .12)
}
```

**Expected behavior**
The .k-cursor-grab selector not to be included in the generated CSS/Sass.

**Comment by NickIliev** [comment]
+1 from t.1677425 there is also an additional CSS class **k-grid-flow-col** which is specific only for KendoReact and can be safely omitted when creating the styles within  **Tile Layout > (div) Tile Layout** 


```CSS
/* ThemeBuidler produced */
.k-tilelayout.k-pos-relative.k-grid-flow-col {
    background-color: var(--kendo-color-app-surface, #000000);
    background-image: none
}

/* Solution */
.k-tilelayout.k-pos-relative {
    background-color: var(--kendo-color-app-surface, #000000);
    background-image: none
}
```
