### ISSUE TITLE
CSS for TabStripItem generates obsolete CSS class k-tabstrip-item and causes styling mismatches

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#131]
**Describe the bug**
In TB Q4 2024 when a style is set for a TabStripItem, the application generates CSS selector that contains CSS class  **k-tabstip-item** (note this class is different from the **k-tabstrip-items** wrapper class)

However, this class is no longer present in the source of truth and is not used in some Telerik/Kendo suites like Telerik Blazor. It is still present in Kedno React which causes the ThemeBuilder's templates and previews to work but only with Kendo React.

**To Reproduce**

- Set custom styles for TabStripItem (e.g. like done here https://themebuilderapp.telerik.com/projects/67459d61f3ce8003cc655a2f )
- Compare the generated SCSS/CSS with the source of truth tests https://github.com/telerik/kendo-themes/blob/develop/tests/tabstrip/tabstrip.html

Source of truth:
![Image](https://github.com/user-attachments/assets/9cc778e8-63b7-486a-b2af-52b9dd139d17)

Blazor rendering for TabStrip position demo:
![Image](https://github.com/user-attachments/assets/d175127f-ad34-4564-b487-22fdfe23e4ca)

TB generated CSS:
![Image](https://github.com/user-attachments/assets/12a83164-5962-4efa-82a1-ca149f95187f)

**Expected behavior**
ThemeBuilder to generate CS that does not contain k-tabstrip-item

**Components technology and version**
Telerik Blazor 7.0.0
ThemeBuilder Q2 2024
Kendo Default Theme 10.0.0

**Additional context**
reported through t.1671577

**Comment by NickIliev** [comment]
Update: The KendoReact team will remove the obsolete CSS class k-tasbstrip-item as discussed [here](https://teams.microsoft.com/l/message/19:3635c0619feb4e8dbc6070237afa789e@thread.skype/1732797390710?tenantId=db266a67-cbe0-4d26-ae1a-d0581fe03535&groupId=1f1434d4-f107-4c4f-808d-6c58db5e3bb5&parentMessageId=1732797390710&teamName=DevTools%20Team&channelName=Kendo-React&createdTime=1732797390710)

**Comment by NickIliev** [comment]
Update: the rendering was updated in the source of truth tests as per https://github.com/telerik/kendo-themes/blame/develop/tests/tabstrip/tabstrip.html#L18 

So now the issue will be fixed in Telerik UI for Blazor, where the **k-tabstrip-item** class should be added.

Will be fixed through https://feedback.telerik.com/blazor/1672602-the-class-k-tabstrip-item-is-missing-in-the-rendering-of-the-tabstrip-component

**Comment by NickIliev** [comment]
+1 from t.1673045 for ASP.NET Core, where the CSS classes are still present.

Consider fixing the issue within ThemeBuilder buy removing the following classes:

**k-tabstrip-item
k-tabstip-items-start** 

```CSS
x
/* 
    Custom solution for the specific rendering difference in the TabStrip in UI for ASP.NET Core 
    We removed the .k-tabstip-items-start and the .k-tabstrip-item CSS classes
    from all generated styles that are related to .k-tabstrip
*/
.k-tabstrip .k-tabstrip-items-wrapper .k-tabstrip-items.k-reset .k-item {
    color: #00156e;
    background-color: initial;
    background-image: none;
    font-size: 12px;
}

.k-tabstrip .k-tabstrip-items-wrapper.k-hstack .k-tabstrip-items.k-reset {
    background-color: #bfdbff;
    background-image: none;
}

.k-tabstrip .k-tabstrip-items-wrapper .k-tabstrip-items.k-reset .k-item.k-focus .k-link,
.k-tabstrip .k-tabstrip-items-wrapper .k-tabstrip-items.k-reset .k-item.k-state-focus .k-link,
.k-tabstrip .k-tabstrip-items-wrapper .k-tabstrip-items.k-reset .k-item.k-state-focused .k-link,
.k-tabstrip .k-tabstrip-items-wrapper .k-tabstrip-items.k-reset .k-item:focus .k-link {
    background-color: whitesmoke;
    background-image: none;
}
```

Logged in UI for ASP>NET Core through https://github.com/telerik/kendo-ui-core/issues/8131
