### ISSUE TITLE
Generated CSS/SCSS for the Filter List Item contains an obsolete "k-textbox" class

### ISSUE THREAD

**Issue by petar-i-todorov** [telerik/themebuilder#138]
**Describe the bug**
Generated CSS/SCSS for the Filter List Item contains an obsolete "k-textbox" class

**To Reproduce**
1. Open a new project.
2. Drill-down to DropDownList, then add a background to the component part "Input" of the template "FILTERLIST ITEM".
3. Observe the change in the Filterable DropDownList in the **Live Preview**.
4. Export the theme.
5. Check the generated SCSS from `_overrides.scss`.
6. Check the source of truth for the [Filterable DropDownList](https://github.com/telerik/kendo-themes/blob/develop/tests/dropdownlist/dropdownlist-filtering.html).

**Actual Results**
Generated SCSS looks like this:
```scss
.k-list-filter .k-searchbox.k-textbox .k-input-inner{
    background-color: lightpink;
    background-image: none;   
}
```
This, however, does not work in other technologies that follow the [source of truth](https://github.com/telerik/kendo-themes/blob/develop/tests/dropdownlist/dropdownlist-filtering.html), such as Kendo Angular, where the "k-textbox" class is not present.

**Expected behavior**
The class "k-textbox" not to be present in the generated CSS.

Reported through t.1675144.
