### ISSUE TITLE
Generated CSS/SCSS for the MultiColumnComboBox contains obsolete ".k-list-container.k-combobox-popup" classes

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#139]
**Describe the bug**
Generated CSS/SCSS for the Filter List Item contains obsolete".k-list-container.k-combobox-popup" classes

**To Reproduce**
- Open a new project.
- Drill down to **MultiColumnComboBox**, then add a background to the component part **"(li) Row"** of the template **"Row > Selected"**.
- Observe the change in the selected row for the MultiColumnComboBox in the Live Preview.
- Export the theme.
- Check the generated SCSS from _overrides.scss.
- Check the source of truth for the [MultiColumnComboBox](https://github.com/telerik/kendo-themes/blob/develop/tests/dropdowngrid/dropdowngrid-opened.html#L45-L50l).

**Actual Results**
Generated SCSS looks like this:
```CSS
.k-popup.k-dropdowngrid-popup.k-list-container.k-combobox-popup .k-data-table .k-table-body .k-table.k-table-list .k-table-row.k-selected {
    background-color: hotpink;
    background-image: none;

}  
```

**Expected behavior**

```CSS
.k-popup.k-dropdowngrid-popup .k-data-table .k-table-body .k-table.k-table-list .k-table-row.k-selected {
    background-color: hotpink;
    background-image: none;

}  
```

**Demo**
https://dojo.telerik.com/nncAxRTl/5

Reported through t.1675818
