### ISSUE TITLE
No exposed template for Input > :focus-within CSS pseudo class

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#142]
**Describe the bug**
The Kendo Bootstrap theme sets a default box shadow effect for the Input with [:focus-within ](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)pseudo class.
However, there is no option to style this pseudo-class through ThemeBuilder which means that there is no option to overwrite the default styles for the Input component (another component that are reusing Input like DropDownList)

**To Reproduce**
As per the issue description in t.1676570

- Create styles for Input
- Check the styles in the demo for UI for Blazor with Kendo Bootstrap
- Check the default styles in the Kendo theme
- 
```CSS
.k-input-solid:focus-within {
    border-color: var(--kendo-color-primary-emphasis, rgba(13, 110, 253, 0.4));
    color: var(--kendo-color-on-app-surface, #212529);
    background-color: var(--kendo-color-app-surface, #ffffff);
    box-shadow: 0 0 0 .25rem color-mix(in srgb, var(--kendo-color-primary, #0d6efd) 25%, transparent)
}

```

**Solution**: Load the above custom CSS after the ThemeBuilder-generated theme. Users can use their own CSS file, or, alternatively, they can use the "External CSS" option to load the custom CSS file and bundle it with the ThemeBuilder theme.

demo: https://blazorrepl.telerik.com/QTaFGVve00Y2ohzO48

**Actual Results**
A blue shadow effect is shown for the focused Inputs and there are no means to remove it from ThemeBuilder.

**Expected behavior**
To have a themebuilder template for :focus-within so that the default style can be modified.

**Screenshots**

![Image](https://github.com/user-attachments/assets/e0a49d2f-0851-4960-a7ee-7d8272a501a8)

**Components technology and version**
TB Q4 2025

**Additional context**
Reported through t.1676570
