### ISSUE TITLE
Settings padding-block & padding-inline for Input does not generate the proper CSS

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#143]
**Describe the bug**
When setting custom values for padding-block and padding-inline through the. "Styles Editor" the generated CSS is not as per the padding property which leads to specificity issues.

**To Reproduce**
1. Go to **Input > Input Normal > (input) Input** component part 
2. Open "Properties" and set any custom **Padding**.
3. Open the "Styles Editor"
4. Add padding-block and padding-inline with any custom values.
5. Export and observe the generated CSS selectors.

**Actual Results**

The CSS selectors for **padding** and for **padding-block**, **padding-inline** are different. At the same time, there is a default style set for padding-block and padding-inline which also differed from the one created in ThemeBuilder
```CSS
input.k-input {
    padding-left: 8px
}
.k-input {
    padding-block: 4px;
    padding-inline: 4px;
}
```

**Expected behavior**

to generate styles with the same CSS selector as the default styles in the Kendo theme
```CSS
input.k-input {
    padding-block: var(--kendo-spacing-1, 0.25rem);
    padding-inline: var(--kendo-spacing-2, 0.5rem)
}
```

**Components technology and version**
TB Q4 Default

**Additional context**
reported through t.1677319
