### ISSUE TITLE
Selected styles are not applying when "scrollable" is set to "none" in the Kendo Grid

### ISSUE THREAD

**Issue by grozevg** [telerik/themebuilder#20]
**Describe the bug**
When the "scrollable" attribute is set to "none" in Kendo Grid, the rendering of the grid changes, and some DOM elements disappear. This causes certain styles not to apply as expected.

**To Reproduce**
1. Open a new ThemeBuilder project
2. Drill-down to the Grid
3. Style the selected row
4. Open a project with a non-scrollable grid 

**Actual Results**
The styles are not applied

**Expected behavior**
The styles to be applied

**Comment by grozevg** [comment]
#1604098

**Comment by rdorris** [comment]
Is there any update to this fix? Notice that a new version 2023.1.425 was released but the problem remains.

**Comment by rdorris** [comment]
Progress?

**Comment by rkirilov** [comment]
Fixed with Q3 2024 release

**Comment by NickIliev** [comment]
The issue is now reproducible with non-scrollable grid in KendoReact + ThemeBuilder Q1 2025

Logged in the KendoReact public repo https://github.com/telerik/kendo-react/issues/2890 

reported through t.1679104

Temporary solution:

explicitly remove the following CSS classes from the generated CSS
```css
.k-table
.k-table-thead
```


Example CSS as generated from ThemeBuilder and as per the source of truth tests:
```CSS
    .k-grid.k-grid-md .k-table .k-table-tbody .k-master-row.k-table-row {
        background-color: purple;
        background-image: none;
        color: white;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row .k-header.k-table-th .k-cell-inner .k-link,
    .k-grid.k-grid-md .k-grid-header .k-table-row .k-header.k-table-th .k-cell-inner .k-link {
        background-color: green;
        background-image: none;
        color: yellow;
    }

    .k-grid.k-grid-md .k-table-tbody .k-master-row.k-table-row.k-selected>td {
        color: lime;
    }

    .k-grid.k-grid-md .k-grouping-header {
        background-color: var(--tb-kendo-color-success-subtle-active);
        background-image: none;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row .k-header.k-table-th.k-sorted .k-cell-inner .k-link .k-sort-icon .k-icon.k-svg-icon.k-svg-i-sort-asc-small>svg,
    .k-grid.k-grid-md .k-grid-header .k-table-row .k-header.k-table-th.k-sorted .k-cell-inner .k-link .k-sort-icon .k-icon.k-svg-icon.k-svg-i-sort-asc-small>svg {
        color: red;
    }

    .k-grid.k-grid-md .k-table-thead .k-table-row.k-filter-row,
    .k-grid.k-grid-md .k-grid-header .k-table-row.k-filter-row {
        background-color: yellow;
        background-image: none;
    }

    .k-grid.k-grid-md .k-table .k-table-group-row.k-grouping-row.k-table-row .k-reset {
        background-color: var(--tb-kendo-color-error-subtle-hover);
        background-image: none;
    }
```

Example code that works for KendoReact grid with **scrollable** set to **none**
https://codesandbox.io/p/sandbox/silly-voice-6nhmm3
