### ISSUE TITLE
Grid > Filter Row styles are rendered with an obsolete class .k-clear-button-visible

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#46]
**Describe the bug**
The exported CSS file does not style the "Clear Filter" icon 

**To Reproduce**
1. Go to 'Grid' and edit the `Filter Row` 
3. Assign custom background colors to the Filter icons
4. As a result, the React preview works, but the generated output fails in UI for Blazor.

**Actual Results**
The generated styles are adding a class called `.k-clear-button-visible` which is not part of the kendo-theme
```CSS
.k-grid.k-grid-md .k-grid-header .k-grid-header-wrap .k-table.k-grid-header-table .k-table-thead .k-table-row.k-filter-row .k-table-th .k-filtercell .k-filtercell-wrapper .k-button.k-button-md.k-button-solid.k-button-solid-base.k-rounded-md.k-icon-button.k-clear-button-visible {
    background-color: #f5f5f5;
    background-image: linear-gradient(#ffc000, #ffc000)
}

```

>tip There is an additional bug in UI for Blazor that also breaks the above CSS (see [here](https://github.com/telerik/blazor/issues/7422)). To properly test the above (and if the Blazor bug is not fixed), replace `k-table-th` with `k-table-td`. Ping me in a private message if more details are needed.

**Expected behavior**
To follow the source of truth where the `.k-clear-button-visible` class is not present

https://github.com/telerik/kendo-themes/blob/v6.4.0/tests/grid/grid-filter-row-blazor.html#L91 
https://github.com/telerik/kendo-themes/blob/v6.4.0/tests/grid/grid-filter-row-blazor.html#L297
https://github.com/telerik/kendo-themes/blob/v6.4.0/tests/grid/grid-filter-row.html#L49

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/18008302/9b857285-bfd4-4855-aeda-d870ae6fdaf6)

**Components technology and version**
Using TB R2 2023
UI for Blazor 4.5.0

**Additional context**
Reported through t.1623502
