### ISSUE TITLE
Option to style the Collapsed state of the whole Expansion Panel component

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#48]
**Description**

Within the **Expansion Panel**, currently, there is only option to style the **collapsed** state of the **Expansion Header**.
However, there is no template for the collapsed state of the whole expansion panel, which means that a custom styling of the **border** (of the whole panel) for the normal expanded state can't be applied to the collapsed state.

**Screenshots**
 
For example:
1. Add a green border with 20px border-radius within the **Expansion Panel > Normal** template.
![image](https://github.com/telerik/themebuilder/assets/18008302/25b83194-85ba-4dac-93a2-599ba9cde75f)

2. Add a red border with border-radius within the **Header > Collapsed** template.
![image](https://github.com/telerik/themebuilder/assets/18008302/a6ac8e47-c309-45e8-9801-fbb279fcb480)

3. As a result, the second border is applied for the header (expected), and there are no means to control the panel's border when it is collapsed
![image](https://github.com/telerik/themebuilder/assets/18008302/360a37be-2a5e-4576-ab5e-94d9b2b167d0)

**Additional context**
Reported through t.1626431 and t.1626432

Currently, behind-the-scenes, setting a border through the **Expansion Panel** template, and its Expander component part creates the following CSS

```CSS
.k-expander.k-expanded {
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
    border-top-left-radius: 20px;
    border-top-right-radius: 20px;
}
```

Temporary solution is to apply the style for the only for the .k-expander class

```CSS
.k-expander {
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
    border-top-left-radius: 20px;
    border-top-right-radius: 20px;
}
```
