### ISSUE TITLE
Wrong CSS hierarchy in Menu > Submenu template

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#58]
**Describe the bug**
The **SubMenu Item** from the **Menu** component improperly inherits the styles from the **Horizontal Root Item** template, where it should have its styles applied. 

The issue is **not** present in the live preview because the React implementation of the Menu component differs in how the nested items are wrapped. However, the bug is present with other Kendo suites like Kendo UI for JQuery, where the animation wrappers are within the child items, and thus, the parent styles take higher priority.

**To Reproduce**
1. Create different styles for **SubMenu Item** and **Horizontal Root Item** 
2. Use the generated theme in [the overview project from Kendo UI for JQuery](https://demos.telerik.com/kendo-ui/menu/index) or alternatively use the following snippet (update the theme link)
```HTML
    <div id="example">
        <div id="megaStore">
            <ul id="horizontalMenu" class="k-header">
                <li>
                    <a>Home</a>
                </li>
                <li>
                    My App
                    <ul >
                        <li>
                            inventory
                            <ul>
                                <li><a>Category</a></li>
                                <li><a>Product</a></li>
                            </ul>
                        </li>
                    </ul>


                </li>
    
            </ul>
        </div>
        <script>
            $(document).ready(function () {
                $("#horizontalMenu").kendoMenu();
            });
        </script>
    </div>
```

>note that the `k-header` class is explicitly present to solve an issue within JQuery logged here https://github.com/telerik/kendo-ui-core/issues/7619

**Actual Results**
![image](https://github.com/telerik/themebuilder/assets/18008302/1dfb3608-f18f-4ad8-8241-cecbb3fadc2a)

```CSS
.k-reset.k-header.k-menu.k-menu-horizontal .k-item.k-menu-item .k-link.k-menu-link {
    row-gap: 0.95rem;
    padding-right: 40px;
    padding-left: 40px;
    background-color: $tb-PurpleDark;
    background-image: none;

}

.k-menu-popup.k-popup .k-menu-group .k-item.k-menu-item .k-link.k-menu-link {
    padding-top: 10px;
    padding-bottom: 10px;
    background-color: $tb-White;
    background-image: none;

}

.k-menu-popup.k-popup .k-menu-group .k-item.k-menu-item .k-link.k-menu-link.k-active,
.k-menu-popup.k-popup .k-menu-group .k-item.k-menu-item .k-link.k-menu-link.k-state-active,
.k-menu-popup.k-popup .k-menu-group .k-item.k-menu-item .k-link.k-menu-link:active {
    background-color: $tb-PurpleDark;
    background-image: none;

}
```

**Expected behavior**
As in the live preview (React)
![image](https://github.com/telerik/themebuilder/assets/18008302/a480b4c1-0f3d-4fa3-a39c-0920673c865c)

**Components technology and version**
ThemeBuilder R2 2023
Kendo UI for JQuery 2023.3.1114

**Additional context**
Reported through t.1632507
