### ISSUE TITLE
(Expansion Panel) Styles from the Focused template are only applied for expanded panels and not for collapsed

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#59]
**Describe the bug**
When a style is being modified in the **Focused** template of the **Expansion Panel**, the generated CSS is only applicable for the expanded state of the panel (but not for the collapsed)

**To Reproduce**
1. Go to 'Expansion Panel' component, and select the **Focused** template
2. Select the' **(div) Expander** root component part
3. Remove the shadow effect.

**Actual Results**
As a result, the shadow effect is removed only for the focused states on expanded panels. but when a panel collapses, the effect is still there.

example for generated CSS (when making a change in the **Focused** template)
```CSS
.k-expander.k-focus.k-expanded,
.k-expander.k-state-focus.k-expanded,
.k-expander.k-state-focused.k-expanded,
.k-expander:focus.k-expanded {
    box-shadow: none
}
```

**Expected behavior**
The effect to be removed for both expanded and collapsed panels, or to have separate templates for collapsed and expanded states.

_Sugested temporary workaround_

```CSS
.k-expander.k-focus,
.k-expander.k-state-focus,
.k-expander.k-state-focused,
.k-expander:focus {
  box-shadow: none;
}

.k-expander.k-focus.k-expanded,
.k-expander.k-state-focus.k-expanded,
.k-expander.k-state-focused.k-expanded,
.k-expander:focus.k-expanded {
    box-shadow: none
}
```

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/18008302/8f844784-1c68-4fe5-8c3c-ae63c4f893c7)

**Components technology and version**
If applicable and related to the Kendo/Telerik components - write the technology and component version.

**Additional context**
Related to the new template introduced through https://github.com/telerik/themebuilder/issues/49 

Reporducible with the Live Preview and with the basic Vue demo https://www.telerik.com/kendo-vue-ui/components/layout/expansionpanel/

reported through t.1633930
