### ISSUE TITLE
ColorGradient > TextBox (HEX) sets only Normal state styles and does not set Hover or Focused styles

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#65]
**Describe the bug**
Currently when styling a hover or focused state of the **ColorGradient > TextBox (HEX) > Hover > (span) TextBox** component part, the styles are always set for the Normal state as follows:

```CSS
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input {

}
```

As a result even when using the Hover or the Focused templates the above CSS is generated (instead of :hover and :focus variants)

**To Reproduce**
1. Go to **ColorGradient > TextBox (HEX) > Hover > (span) TextBox**
2. Change the Border color

Result: the color applies not only to the Hover template but also to all other states (Normal, Hover, Focused) and behind the scenes the following CSS is generated 
```CSS
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input {

}
```

**Expected behavior**
To generate styles for each different state

For example, the above works for both React and JQuery (there are rendering differences compared to the source of truth https://github.com/telerik/kendo-themes/blob/e2d5c5a08efe3d7ba9bb5a5c9666d7f2aab15d3d/tests/colorgradient/colorgradient-modes.html#L295-L296)

```CSS
/* normal state */
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input-solid,
.k-colorgradient .k-colorgradient-inputs .k-textbox.k-input-solid {
    border-bottom-color: red;
    border-left-color: red;
    border-right-color: red;
    border-top-color: red;
}

/* hover state */
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input-solid.k-hover,
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input-solid:hover,
.k-colorgradient .k-colorgradient-inputs .k-textbox.k-input-solid.k-hover,
.k-colorgradient .k-colorgradient-inputs .k-textbox.k-input-solid:hover {
    border-bottom-color: blue;
    border-left-color: blue;
    border-right-color: blue;
    border-top-color: blue;
}

/* focused state */
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input-solid.k-focus,
.k-colorgradient .k-colorgradient-inputs .k-hex-value.k-textbox.k-input-solid:focus,
.k-colorgradient .k-colorgradient-inputs .k-textbox.k-input-solid.k-focus,
.k-colorgradient .k-colorgradient-inputs .k-textbox.k-input-solid:focus {
    border-bottom-color: green;
    border-left-color: green;
    border-right-color: green;
    border-top-color: green;
}
```

**Additional context**
Reported through t.1638127
