### ISSUE TITLE
MultiViewCalendar / Calendar renders obsolete class k-content

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#82]
**Describe the bug**
Currently, the ThemeBuilder template for **MultiViewCalendar** produces styles based on the `k-content` selector. However, this selector is abandoned in the source of truth tests in favor of the `k-calendar-table` selector. 

The Live Preview works, because Kendo React is the only entire which uses `k-calendar-table` and `k-content` - probably as a legacy because even the source of truth test for React are no longer using the `k-content`.

As a result, instead of using `k-calendar-table` (used by all source of truth tests), we are relying on `k-content` which means that the MultiViewCalendar can't be styled properly.

+ Probably the same issue within the **Calendar** component

**To Reproduce**
1. Go to 'MultiViewCalendar'
2. Modify some styles within the content part (e.g. day cells)
3.  Export and observe the generated CSS and then compare it to the React source of truth 

https://github.com/telerik/kendo-themes/blob/develop/tests/multiviewcalendar/multiviewcalendar-react.html#L41

**Actual Results**
Using the obsolete `k-content` instead of `k-calendar-table`.

```CSS
.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-view.k-calendar-monthview .k-content .k-calendar-td .k-link {
    background-color: green;
    background-image: none;
    color: #fff
}

.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-view.k-calendar-monthview .k-content .k-calendar-td.k-selected .k-link {
    background-color: blue;
    background-image: none
}

.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-header.k-hstack .k-button.k-button-md.k-button-flat.k-button-flat-base.k-rounded-md.k-calendar-title,
.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-header.k-hbox .k-button.k-button-md.k-button-flat.k-button-flat-base.k-rounded-md.k-calendar-title {
    background-color: purple !important;
    background-image: none !important;
    color: #fff
}

.my-multi-calendar.k-calendar-range .k-calendar-view.k-calendar-monthview .k-content .k-calendar-td .k-link {
    background-color: pink;
    background-image: none;
    color: blue
}
```

**Expected behavior**
To replace the `k-content` with `k-calendar-table` - this would resolve the **MultiVIewCalendar** styling issues in multiple Kendo/Telerik suites. 

Note also in the third entry that there are also differences related to missing `.k-hstack` and `.k-hbox` when `k-calendar-header` is used to render a header section https://github.com/telerik/kendo-themes/blob/develop/tests/multiviewcalendar/multiviewcalendar-react.html#L15

```CSS
.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-view.k-calendar-monthview .k-calendar-table .k-calendar-td .k-link {
    background-color: green;
    background-image: none;
    color: #fff
}

.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-view.k-calendar-monthview .k-calendar-table .k-calendar-td.k-selected .k-link {
    background-color: blue;
    background-image: none
}

.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-header.k-hstack .k-button.k-button-md.k-button-flat.k-button-flat-base.k-rounded-md.k-calendar-title, 
.my-multi-calendar.k-calendar.k-calendar-range .k-calendar-header.k-hbox .k-button.k-button-md.k-button-flat.k-button-flat-base.k-rounded-md.k-calendar-title {
    background-color: purple !important;
    background-image: none !important;
    color: #fff
}

.my-multi-calendar .k-button.k-calendar-nav-today.k-button-flat.k-rounded-md.k-button-md.k-button-flat-primary {
    background-color: yellow !important;
    background-image: none !important;
    color: cadetblue;
}
```

**Components technology and version**
TB Q1 2024

**Additional context**
Reported through t.1642465
